In [53]:
%matplotlib inline
import numpy as np
import pandas as pd



How likely is it that you roll doubles when rolling two dice?

In [130]:
rolls = np.random.choice([1,2,3,4,5,6], size = (10_000, 2))
rolls

array([[2, 4],
       [5, 2],
       [4, 2],
       ...,
       [4, 6],
       [5, 1],
       [5, 4]])

In [140]:
df = pd.DataFrame(rolls)

In [141]:
df = df.apply(lambda x: True if x[0] == x[1] else False, axis =1) 

In [139]:
#likelyhood that you roll doubles when rolling two dice
df.mean()

0.1671

If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?
1 = heads, 0 = tails

In [142]:
flips = np.random.choice([1,0], size = (10_000, 8))
flips

array([[1, 1, 1, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 1, 1],
       ...,
       [0, 0, 0, ..., 0, 1, 1],
       [0, 0, 1, ..., 0, 1, 0],
       [0, 1, 0, ..., 1, 0, 0]])

In [148]:
df1 = pd.DataFrame(flips)


In [145]:
df1 = df1.apply(lambda x: True if x.sum() == 3 else False, axis=1)

In [146]:
#probability of getting exactly 3 heads
df1.mean()

0.2162

In [150]:
df2 = pd.DataFrame(flips)
df2 = df1.apply(lambda x: True if x.sum() > 3 else False, axis=1)

In [151]:
#probability of getting more than 3 heads
df2.mean()

0.6382

There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

ds = 1, web = 0

In [152]:
#ds = 1, web = 0
bb = np.random.choice([1,0], size = (10_000, 2), p=[1/4, 3/4])

In [153]:
bb1 = pd.DataFrame(bb)

In [156]:
bb2 = bb1.apply(lambda x: True if x.sum()==2 else False, axis =1).mean()

#probability of two billboards I drive past both have data science students on them
bb2

0.0618

Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [167]:
poptarts = np.random.normal(3, (1.5), (100000,5))

In [168]:
poptarts = pd.DataFrame(poptarts)

In [173]:
poptarts1 = poptarts.apply(lambda x: True if x.sum() <= 16 else False, axis =1).mean()
# how likely is it that I will be able to buy some poptarts on Friday afternoon?
poptarts1

0.61833

Compare Heights

Men have an average height of 178 cm and standard deviation of 8cm.
Women have a mean of 170, sd = 6cm.
If a man and woman are chosen at random, P(woman taller than man)?

In [165]:
h_men = np.random.normal(178, 8, 10000)
h_women = np.random.normal(170, 6, 10000)
h_men

array([173.8450272 , 182.87415527, 177.5396306 , ..., 188.6083554 ,
       175.84039185, 172.15101311])

In [166]:
P_taller = (h_women > h_men).mean()
P_taller

0.2082

When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

What is the probability that we observe an installation issue within the first 150 students that download anaconda?

How likely is it that 450 students all download anaconda without an issue?
fail = 0, not fail =1

In [ ]:
installation = np.random.choice([1,0], size =(10000, 50), p = [249/250, 1/250])

In [ ]:
installation = pd.DataFrame(installation)

In [ ]:
installation

In [ ]:
(installation.sum(axis =1)==50).mean()

In [ ]:
# for 100 students
installation100 = np.random.choice([1,0], size =(10000, 100), p = [249/250, 1/250])

In [ ]:
installation100 = pd.DataFrame(installation100)

In [ ]:
(installation100.sum(axis =1)==100).mean()

In [175]:
#What is the probability that we observe an installation issue within the first 150 students that download anaconda?

installation150 = np.random.choice([1,0], size =(10000, 150), p = [249/250, 1/250])

In [176]:
installation150 = pd.DataFrame(installation150)

In [177]:
(installation150.sum(axis =1) <150).mean()

0.4469

In [181]:
#How likely is it that 450 students all download anaconda without an issue?
installation450 = np.random.choice([1,0], size =(10000, 450), p = [249/250, 1/250])


In [182]:
installation450 = pd.DataFrame(installation450)

In [183]:
(installation450.sum(axis =1) ==450).mean()

0.1655

There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?
1 = no truck, 0 = truck



In [197]:
truck = np.random.choice([1,0], size =(10000,3), p = [0.7, 0.3])

In [198]:
truck = pd.DataFrame(truck)

In [199]:
truck

0  1  2
0     1  1  1
1     1  1  1
2     0  1  1
3     0  1  0
4     0  0  0
...  .. .. ..
9995  1  0  1
9996  1  0  1
9997  1  1  0
9998  1  0  0
9999  0  1  1

[10000 rows x 3 columns]

In [204]:
p_truck = truck.apply(lambda x: 1 if x.sum()==0 else 0, axis =1)
p_truck.mean()

0.0284

How likely is it that a food truck will show up sometime this week?

In [205]:
truck1 = np.random.choice([1,0], size =(10000,7), p = [0.7, 0.3])

In [206]:
truck1

array([[1, 1, 1, ..., 1, 1, 0],
       [1, 1, 1, ..., 0, 1, 1],
       [1, 1, 1, ..., 0, 1, 1],
       ...,
       [1, 0, 1, ..., 1, 1, 0],
       [1, 0, 1, ..., 1, 1, 1],
       [1, 1, 0, ..., 1, 1, 1]])

In [207]:
(truck1.sum(axis =1) > 1).mean()

0.9963

If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [ ]:
bday = np.random.choice(range(1,366), size = (100000,23))

In [ ]:
bday = pd.DataFrame(bday)
bday

In [ ]:
bday = bday.astype(int)
bday

In [ ]:
bday['count'] = bday.nunique(axis =1)
bday

In [ ]:
bday['match'] = bday.apply(lambda x: 1 if (x['count'] < 23) else 0, axis =1)

In [ ]:
bday

In [ ]:
bday.match.mean()

What if it's 20 people? 40?

In [ ]:
bday20 = np.random.choice(range(1,366), size = (100000,20))

In [ ]:
bday20 = pd.DataFrame(bday20)

In [ ]:
bday20['count'] = bday20.nunique(axis =1)

In [ ]:
bday20['match'] = bday20.apply(lambda x: 1 if x['count']<20 else 0, axis =1)

In [ ]:
bday20.match.mean()

In [ ]:
bday40 = np.random.choice(range(1,366), size = (100000,40))

In [ ]:
bday40 = pd.DataFrame(bday40)

In [ ]:
bday40['count'] = bday40.nunique(axis =1)


In [ ]:
bday40['match'] = bday40.apply(lambda x: 1 if x['count']<40 else 0, axis =1)

In [ ]:
bday40.match.mean()

Let's use what we've learned to play a mage duel!

Imagine your wizard has 6d4 health points and you have spells that do 6d4 damage. "6d4" means rolling six 4-sided dice and summing the result.

Your opposing mage has 4d6 health points and spells that do 4d6. "4d6" means rolling four six-sided dice and summing the result.

Exercises

Simulate mage duels to answer who is the more powerful mage?

Before running simulations, do you have a hypothesis of which mage will win? Do you have a hunch? Write it down. This is your first exercise.
Simulate 10 mage duels. Is there a clear winner? Run that 10 duel simulation again. Was the answer similar?
Do the results change much at 100 duels?
Now, simulate 10,000 mage duels. Is there a clear winner?

In [125]:
mage1_win_count = 0
mage2_win_count = 0
draws = 0
no_winner = 0
for i in range(1,10001):
    mage1hp = np.random.choice(range(1,7), size = (1,4)).sum()
    mage2hp = np.random.choice(range(1,5), size = (1,6)).sum()
    winner = 'none'
    #print(f'mage1hp = {mage1hp}')
    #print(f'mage2hp = {mage2hp}')
    while mage2hp>0 and mage1hp > 0:
        mage1at = np.random.choice(range(1,7), size = (1,4))
        mage2at = np.random.choice(range(1,5), size = (1,6))
        mage1hp = mage1hp - mage2at.sum()
        mage2hp = mage2hp - mage1at.sum()
      
        if mage1hp <= 0 and mage2hp > 0:
            winner = 'mage2'
            mage1_win_count += 1
            #print(winner)
            break
        elif mage2hp <= 0 and mage1hp > 0:
            winner = 'mage1'
            mage2_win_count += 1
            #print(winner)
            break
        elif mage1hp <= 0 and mage2hp <= 0:
            winner = 'draw'
            draws = draws + 1
            #print(winner)
            break
    i = i + 1

print(f'mage1_winner_count = {mage1_win_count}')
print(f'mage2_winner_count = {mage2_win_count}')
print(f'draws = {draws}')


mage1_winner_count = 3414
mage2_winner_count = 1658
draws = 4928


In [129]:
mage1_win_count = 0
mage2_win_count = 0
draws = 0
no_winner = 0
for i in range(1,10_001):
    mage1hp = np.random.choice(range(1,7), size = (1,4)).sum()
    mage2hp = np.random.choice(range(1,5), size = (1,6)).sum()
    winner = 'none'
    #print(f'mage1hp = {mage1hp}')
    #print(f'mage2hp = {mage2hp}')
    while mage2hp>0 and mage1hp > 0:
        
        mage1at = np.random.choice(range(1,7), size = (1,4))
        mage2at = np.random.choice(range(1,5), size = (1,6))
        
        mage1hp = mage1hp - mage2at.sum()
        if mage1hp <= 0 and mage2hp > 0:
            winner = 'mage2'
            mage2_win_count += 1
            #print(winner)
            break
             
        mage2hp = mage2hp - mage1at.sum()

        if mage2hp <= 0 and mage1hp > 0:
            winner = 'mage1'
            mage1_win_count += 1
            #print(winner)
            break
       

#         elif mage1hp <= 0 and mage2hp <= 0:
#             winner = 'draw'
#             draws = draws + 1
#             #print(winner)
#             break
    i = i + 1

print(f'mage1_winner_count = {mage1_win_count}')
print(f'mage2_winner_count = {mage2_win_count}')
print(f'draws = {draws}')



mage1_winner_count = 1783
mage2_winner_count = 8217
draws = 0
