In [3]:
%matplotlib inline
import numpy as np
import pandas as pd



How likely is it that you roll doubles when rolling two dice?

In [7]:
rolls = np.random.choice([1,2,3,4,5,6], size = (10_000, 2))
rolls

array([[6, 5],
       [1, 5],
       [4, 1],
       ...,
       [2, 4],
       [2, 1],
       [4, 3]])

In [11]:
df = pd.DataFrame(rolls)
df

0  1
0     6  5
1     1  5
2     4  1
3     5  3
4     4  1
...  .. ..
9995  6  2
9996  1  5
9997  2  4
9998  2  1
9999  4  3

[10000 rows x 2 columns]

In [16]:
df = df.apply(lambda x: True if x[0] == x[1] else False, axis =1)    

In [18]:
df.mean()

0.1667

If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?
1 = heads, 0 = tails

In [55]:
flips = np.random.choice([1,0], size = (10_000, 8))
flips



array([[1, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 1, 0, 1],
       [1, 1, 1, ..., 1, 1, 0],
       ...,
       [1, 1, 1, ..., 1, 0, 0],
       [1, 0, 1, ..., 1, 0, 1],
       [0, 0, 1, ..., 1, 0, 0]])

In [56]:
df1 = pd.DataFrame(flips)
df1

0  1  2  3  4  5  6  7
0     1  1  0  1  1  0  0  0
1     0  1  0  0  0  1  0  1
2     1  1  1  0  0  1  1  0
3     0  0  0  0  0  0  1  1
4     0  0  0  1  0  1  1  0
...  .. .. .. .. .. .. .. ..
9995  1  1  0  1  1  0  0  0
9996  0  0  1  1  1  1  0  1
9997  1  1  1  1  1  1  0  0
9998  1  0  1  1  0  1  0  1
9999  0  0  1  0  1  1  0  0

[10000 rows x 8 columns]

In [48]:
df1 = df1.apply(lambda x: True if (x[0]+x[1]+x[2]+x[3]+x[4]+x[5]+x[6]+x[7] == 3) else False, axis=1)

In [50]:
df1.mean()

0.2176

In [57]:
df2 = df1.apply(lambda x: True if (x[0]+x[1]+x[2]+x[3]+x[4]+x[5]+x[6]+x[7] > 3) else False, axis=1)

In [58]:
df2.mean()

0.6387

There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

ds = 1, web = 0

In [59]:
bb = np.random.choice([1,0], size = (10_000, 2), p=[1/4, 3/4])



In [60]:
bb1 = pd.DataFrame(bb)
bb1

In [65]:
bb2 = bb1.apply(lambda x: True if x[0]+x[1]==2 else False, axis =1)

In [67]:
bb2.mean()

0.0628

Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [95]:
pop = np.random.normal(3, (1.5), (100000,5))

In [96]:
pop1 = pd.DataFrame(pop)

In [97]:
pop1

0         1         2         3         4
0      1.700623  1.317306  2.466469  3.388991  2.034570
1      2.515138  2.366805  1.691867  3.093626  3.010965
2      2.729580  5.227399  4.070548  2.445914  2.884193
3      2.356788  2.791586  1.557889  2.873987  2.732154
4      3.539811  1.513891  2.179262  2.341704  3.679853
...         ...       ...       ...       ...       ...
99995  1.693646  3.927310  3.384162  1.044565  1.368031
99996  5.279165  2.295229  0.848012  3.940836  4.738193
99997  4.366254  1.774370  3.981708  3.095369  1.468519
99998  3.726763  2.628301  3.109584  3.168861  3.197429
99999  3.573399  3.997291  2.616306  1.392459  2.540492

[100000 rows x 5 columns]

In [100]:
pop2 = pop1.apply(lambda x: True if (x[0]+x[1]+x[2]+x[3]+x[4]<=16) else False, axis =1)

In [101]:
pop2.mean()

0.61718

Compare Heights

Men have an average height of 178 cm and standard deviation of 8cm.
Women have a mean of 170, sd = 6cm.
If a man and woman are chosen at random, P(woman taller than man)?

In [113]:
h_men = np.random.normal(178, 8, 10000)
h_women = np.random.normal(170, 6, 10000)
h_men

array([163.7218289 , 185.64183513, 190.28977387, ..., 181.97558117,
       179.10302163, 178.30657689])

In [117]:
(h_women > h_men).mean()

0.2131

When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

What is the probability that we observe an installation issue within the first 150 students that download anaconda?

How likely is it that 450 students all download anaconda without an issue?
fail = 0, not fail =1

In [122]:
installation = np.random.choice([1,0], size =(10000, 50), p = [249/250, 1/250])

In [123]:
installation = pd.DataFrame(installation)

In [124]:
installation

0   1   2   3   4   5   6   7   8   9   ...  40  41  42  43  44  45  46  \
0      1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   
1      1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   
2      1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   
3      1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   
4      1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
9995   1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   
9996   1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   
9997   1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   
9998   1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   
9999   1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   

      47  48  49  
0      1   1   1  
1      1   1   1  
2      1   1   1  
3      1   1   1  
4      1   1   1  
...   ..  ..  ..  
9995   1   1   1  
9996   1   1   1  
9997   0   1   1  
9998   1   1   1  
9999   1   1   1  

[10000 rows x 50 columns]

In [133]:
(installation.sum(axis =1)==50).mean()

0.8176

In [130]:
# for 100 students
installation100 = np.random.choice([1,0], size =(10000, 100), p = [249/250, 1/250])

In [131]:
installation100 = pd.DataFrame(installation100)

In [134]:
(installation100.sum(axis =1)==100).mean()

0.6678

In [140]:
#What is the probability that we observe an installation issue within the first 150 students that download anaconda?

installation150 = np.random.choice([1,0], size =(10000, 150), p = [249/250, 1/250])

In [141]:
installation150 = pd.DataFrame(installation150)

In [142]:
(installation150.sum(axis =1) <150).mean()

0.4528

In [143]:
#How likely is it that 450 students all download anaconda without an issue?
installation450 = np.random.choice([1,0], size =(10000, 450), p = [249/250, 1/250])


In [144]:
installation450 = pd.DataFrame(installation450)

In [146]:
(installation450.sum(axis =1) ==450).mean()

0.1673

There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?
1 = no truck, 0 = truck



In [18]:
truck = np.random.choice([1,0], size =(10000,3), p = [0.3, 0.7])

In [19]:
truck = pd.DataFrame(truck)

In [20]:
truck

0  1  2
0     0  0  1
1     0  0  0
2     0  0  1
3     0  0  0
4     0  1  1
...  .. .. ..
9995  1  0  0
9996  0  0  0
9997  0  0  0
9998  0  1  0
9999  0  1  0

[10000 rows x 3 columns]

In [21]:
(truck.sum(axis=1)!= 0).mean()

0.6594

How likely is it that a food truck will show up sometime this week?

In [22]:
truck1 = np.random.choice([1,0], size =(10000,7), p = [0.3, 0.7])

In [23]:
truck1

array([[0, 1, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]])

In [30]:
(truck1.sum(axis =1)<7).mean()

0.9995

If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [107]:
bday = np.random.choice(range(1,366), size = (100000,23))

In [108]:
bday = pd.DataFrame(bday)
bday

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0      354  251  329  214  340  194  258  268  113    9  ...  329  306  186   
1       62  150  231  289  234  184  273  362  254  313  ...  227  121  348   
2       26  248  337  363  340  298  321  208  138  117  ...   80   81  127   
3      319  354  173    6  291  127  354  216  112  286  ...  209  355  244   
4       84  273  343  203  361  354  283  106  238  195  ...   25  337  123   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
99995    8  153   86   80  259  329  358  199   54   14  ...  287   95  153   
99996  285  230   36  277   12   44   44  283  250  221  ...  312  175  151   
99997  254  336  298  297  202  242   75  349  289  131  ...  153  295  218   
99998  356  107  243  166  175   65  247  199  266  108  ...  335   85  350   
99999  210  287  318   39   36   24   31  128  123  201  ...   30  241  300   

        16   17   18   19   20   21   22  
0      354  181  325  276  195  227   20  
1      293  166   83  279  262  165   34  
2      308   11  289  219    3  344   15  
3      193  156  108  312  210   75    7  
4      214   11  294  296  307   76  257  
...    ...  ...  ...  ...  ...  ...  ...  
99995  365  272  253  108  112   14    8  
99996  328  172  277  229   29  275  255  
99997   14  131  293  321   75  101  218  
99998  139  111  194  326   26  250  351  
99999  273  152  105   17   85  346  326  

[100000 rows x 23 columns]

In [109]:
bday = bday.astype(int)
bday

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0      354  251  329  214  340  194  258  268  113    9  ...  329  306  186   
1       62  150  231  289  234  184  273  362  254  313  ...  227  121  348   
2       26  248  337  363  340  298  321  208  138  117  ...   80   81  127   
3      319  354  173    6  291  127  354  216  112  286  ...  209  355  244   
4       84  273  343  203  361  354  283  106  238  195  ...   25  337  123   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
99995    8  153   86   80  259  329  358  199   54   14  ...  287   95  153   
99996  285  230   36  277   12   44   44  283  250  221  ...  312  175  151   
99997  254  336  298  297  202  242   75  349  289  131  ...  153  295  218   
99998  356  107  243  166  175   65  247  199  266  108  ...  335   85  350   
99999  210  287  318   39   36   24   31  128  123  201  ...   30  241  300   

        16   17   18   19   20   21   22  
0      354  181  325  276  195  227   20  
1      293  166   83  279  262  165   34  
2      308   11  289  219    3  344   15  
3      193  156  108  312  210   75    7  
4      214   11  294  296  307   76  257  
...    ...  ...  ...  ...  ...  ...  ...  
99995  365  272  253  108  112   14    8  
99996  328  172  277  229   29  275  255  
99997   14  131  293  321   75  101  218  
99998  139  111  194  326   26  250  351  
99999  273  152  105   17   85  346  326  

[100000 rows x 23 columns]

In [110]:
bday['count'] = bday.nunique(axis =1)
bday

0    1    2    3    4    5    6    7    8    9  ...   14   15   16  \
0      354  251  329  214  340  194  258  268  113    9  ...  306  186  354   
1       62  150  231  289  234  184  273  362  254  313  ...  121  348  293   
2       26  248  337  363  340  298  321  208  138  117  ...   81  127  308   
3      319  354  173    6  291  127  354  216  112  286  ...  355  244  193   
4       84  273  343  203  361  354  283  106  238  195  ...  337  123  214   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
99995    8  153   86   80  259  329  358  199   54   14  ...   95  153  365   
99996  285  230   36  277   12   44   44  283  250  221  ...  175  151  328   
99997  254  336  298  297  202  242   75  349  289  131  ...  295  218   14   
99998  356  107  243  166  175   65  247  199  266  108  ...   85  350  139   
99999  210  287  318   39   36   24   31  128  123  201  ...  241  300  273   

        17   18   19   20   21   22  count  
0      181  325  276  195  227   20     20  
1      166   83  279  262  165   34     23  
2       11  289  219    3  344   15     23  
3      156  108  312  210   75    7     22  
4       11  294  296  307   76  257     23  
...    ...  ...  ...  ...  ...  ...    ...  
99995  272  253  108  112   14    8     20  
99996  172  277  229   29  275  255     21  
99997  131  293  321   75  101  218     20  
99998  111  194  326   26  250  351     23  
99999  152  105   17   85  346  326     23  

[100000 rows x 24 columns]

In [111]:
bday['match'] = bday.apply(lambda x: 1 if (x['count'] < 23) else 0, axis =1)

In [112]:
bday

0    1    2    3    4    5    6    7    8    9  ...   15   16   17  \
0      354  251  329  214  340  194  258  268  113    9  ...  186  354  181   
1       62  150  231  289  234  184  273  362  254  313  ...  348  293  166   
2       26  248  337  363  340  298  321  208  138  117  ...  127  308   11   
3      319  354  173    6  291  127  354  216  112  286  ...  244  193  156   
4       84  273  343  203  361  354  283  106  238  195  ...  123  214   11   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
99995    8  153   86   80  259  329  358  199   54   14  ...  153  365  272   
99996  285  230   36  277   12   44   44  283  250  221  ...  151  328  172   
99997  254  336  298  297  202  242   75  349  289  131  ...  218   14  131   
99998  356  107  243  166  175   65  247  199  266  108  ...  350  139  111   
99999  210  287  318   39   36   24   31  128  123  201  ...  300  273  152   

        18   19   20   21   22  count  match  
0      325  276  195  227   20     20      1  
1       83  279  262  165   34     23      0  
2      289  219    3  344   15     23      0  
3      108  312  210   75    7     22      1  
4      294  296  307   76  257     23      0  
...    ...  ...  ...  ...  ...    ...    ...  
99995  253  108  112   14    8     20      1  
99996  277  229   29  275  255     21      1  
99997  293  321   75  101  218     20      1  
99998  194  326   26  250  351     23      0  
99999  105   17   85  346  326     23      0  

[100000 rows x 25 columns]

In [113]:
bday.match.mean()

0.50794

What if it's 20 people? 40?

In [123]:
bday20 = np.random.choice(range(1,366), size = (100000,20))

In [124]:
bday20 = pd.DataFrame(bday20)

In [125]:
bday20['count'] = bday20.nunique(axis =1)

In [126]:
bday20['match'] = bday20.apply(lambda x: 1 if x['count']<20 else 0, axis =1)

In [127]:
bday20.match.mean()

0.41182

In [134]:
bday40 = np.random.choice(range(1,366), size = (100000,40))

In [135]:
bday40 = pd.DataFrame(bday40)

In [136]:
bday40['count'] = bday40.nunique(axis =1)


In [138]:
bday40['match'] = bday40.apply(lambda x: 1 if x['count']<40 else 0, axis =1)

In [139]:
bday40.match.mean()

0.89155