In [4]:
%matplotlib inline
import numpy as np
import pandas as pd



How likely is it that you roll doubles when rolling two dice?

In [7]:
rolls = np.random.choice([1,2,3,4,5,6], size = (10_000, 2))
rolls

array([[6, 5],
       [1, 5],
       [4, 1],
       ...,
       [2, 4],
       [2, 1],
       [4, 3]])

In [11]:
df = pd.DataFrame(rolls)
df

0  1
0     6  5
1     1  5
2     4  1
3     5  3
4     4  1
...  .. ..
9995  6  2
9996  1  5
9997  2  4
9998  2  1
9999  4  3

[10000 rows x 2 columns]

In [16]:
df = df.apply(lambda x: True if x[0] == x[1] else False, axis =1)    

In [18]:
df.mean()

0.1667

If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?
1 = heads, 0 = tails

In [55]:
flips = np.random.choice([1,0], size = (10_000, 8))
flips



array([[1, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 1, 0, 1],
       [1, 1, 1, ..., 1, 1, 0],
       ...,
       [1, 1, 1, ..., 1, 0, 0],
       [1, 0, 1, ..., 1, 0, 1],
       [0, 0, 1, ..., 1, 0, 0]])

In [56]:
df1 = pd.DataFrame(flips)
df1

0  1  2  3  4  5  6  7
0     1  1  0  1  1  0  0  0
1     0  1  0  0  0  1  0  1
2     1  1  1  0  0  1  1  0
3     0  0  0  0  0  0  1  1
4     0  0  0  1  0  1  1  0
...  .. .. .. .. .. .. .. ..
9995  1  1  0  1  1  0  0  0
9996  0  0  1  1  1  1  0  1
9997  1  1  1  1  1  1  0  0
9998  1  0  1  1  0  1  0  1
9999  0  0  1  0  1  1  0  0

[10000 rows x 8 columns]

In [48]:
df1 = df1.apply(lambda x: True if (x[0]+x[1]+x[2]+x[3]+x[4]+x[5]+x[6]+x[7] == 3) else False, axis=1)

In [50]:
df1.mean()

0.2176

In [57]:
df2 = df1.apply(lambda x: True if (x[0]+x[1]+x[2]+x[3]+x[4]+x[5]+x[6]+x[7] > 3) else False, axis=1)

In [58]:
df2.mean()

0.6387

There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

ds = 1, web = 0

In [59]:
bb = np.random.choice([1,0], size = (10_000, 2), p=[1/4, 3/4])



In [60]:
bb1 = pd.DataFrame(bb)
bb1

In [65]:
bb2 = bb1.apply(lambda x: True if x[0]+x[1]==2 else False, axis =1)

In [67]:
bb2.mean()

0.0628

Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [95]:
pop = np.random.normal(3, (1.5), (100000,5))

In [96]:
pop1 = pd.DataFrame(pop)

In [97]:
pop1

0         1         2         3         4
0      1.700623  1.317306  2.466469  3.388991  2.034570
1      2.515138  2.366805  1.691867  3.093626  3.010965
2      2.729580  5.227399  4.070548  2.445914  2.884193
3      2.356788  2.791586  1.557889  2.873987  2.732154
4      3.539811  1.513891  2.179262  2.341704  3.679853
...         ...       ...       ...       ...       ...
99995  1.693646  3.927310  3.384162  1.044565  1.368031
99996  5.279165  2.295229  0.848012  3.940836  4.738193
99997  4.366254  1.774370  3.981708  3.095369  1.468519
99998  3.726763  2.628301  3.109584  3.168861  3.197429
99999  3.573399  3.997291  2.616306  1.392459  2.540492

[100000 rows x 5 columns]

In [100]:
pop2 = pop1.apply(lambda x: True if (x[0]+x[1]+x[2]+x[3]+x[4]<=16) else False, axis =1)

In [101]:
pop2.mean()

0.61718

Compare Heights

Men have an average height of 178 cm and standard deviation of 8cm.
Women have a mean of 170, sd = 6cm.
If a man and woman are chosen at random, P(woman taller than man)?

In [113]:
h_men = np.random.normal(178, 8, 10000)
h_women = np.random.normal(170, 6, 10000)
h_men

array([163.7218289 , 185.64183513, 190.28977387, ..., 181.97558117,
       179.10302163, 178.30657689])

In [117]:
(h_women > h_men).mean()

0.2131

When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

What is the probability that we observe an installation issue within the first 150 students that download anaconda?

How likely is it that 450 students all download anaconda without an issue?
fail = 0, not fail =1

In [122]:
installation = np.random.choice([1,0], size =(10000, 50), p = [249/250, 1/250])

In [123]:
installation = pd.DataFrame(installation)

In [124]:
installation

0   1   2   3   4   5   6   7   8   9   ...  40  41  42  43  44  45  46  \
0      1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   
1      1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   
2      1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   
3      1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   
4      1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
9995   1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   
9996   1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   
9997   1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   
9998   1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   
9999   1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   

      47  48  49  
0      1   1   1  
1      1   1   1  
2      1   1   1  
3      1   1   1  
4      1   1   1  
...   ..  ..  ..  
9995   1   1   1  
9996   1   1   1  
9997   0   1   1  
9998   1   1   1  
9999   1   1   1  

[10000 rows x 50 columns]

In [133]:
(installation.sum(axis =1)==50).mean()

0.8176

In [130]:
# for 100 students
installation100 = np.random.choice([1,0], size =(10000, 100), p = [249/250, 1/250])

In [131]:
installation100 = pd.DataFrame(installation100)

In [134]:
(installation100.sum(axis =1)==100).mean()

0.6678

In [ ]:
#What is the probability that we observe an installation issue within the first 150 students that download anaconda?

